'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Code_128_Barcode_Generator_v2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11011001100.
        '''</summary>
        Friend ReadOnly Property a0() As String
            Get
                Return ResourceManager.GetString("a0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11001101100.
        '''</summary>
        Friend ReadOnly Property a1() As String
            Get
                Return ResourceManager.GetString("a1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11001000100.
        '''</summary>
        Friend ReadOnly Property a10() As String
            Get
                Return ResourceManager.GetString("a10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10111101110.
        '''</summary>
        Friend ReadOnly Property a100() As String
            Get
                Return ResourceManager.GetString("a100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11101011110.
        '''</summary>
        Friend ReadOnly Property a101() As String
            Get
                Return ResourceManager.GetString("a101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11110101110.
        '''</summary>
        Friend ReadOnly Property a102() As String
            Get
                Return ResourceManager.GetString("a102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11000100100.
        '''</summary>
        Friend ReadOnly Property a11() As String
            Get
                Return ResourceManager.GetString("a11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10110011100.
        '''</summary>
        Friend ReadOnly Property a12() As String
            Get
                Return ResourceManager.GetString("a12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10011011100.
        '''</summary>
        Friend ReadOnly Property a13() As String
            Get
                Return ResourceManager.GetString("a13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10011001110.
        '''</summary>
        Friend ReadOnly Property a14() As String
            Get
                Return ResourceManager.GetString("a14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10111001100.
        '''</summary>
        Friend ReadOnly Property a15() As String
            Get
                Return ResourceManager.GetString("a15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10011101100.
        '''</summary>
        Friend ReadOnly Property a16() As String
            Get
                Return ResourceManager.GetString("a16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10011100110.
        '''</summary>
        Friend ReadOnly Property a17() As String
            Get
                Return ResourceManager.GetString("a17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11001110010.
        '''</summary>
        Friend ReadOnly Property a18() As String
            Get
                Return ResourceManager.GetString("a18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11001011100.
        '''</summary>
        Friend ReadOnly Property a19() As String
            Get
                Return ResourceManager.GetString("a19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11001100110.
        '''</summary>
        Friend ReadOnly Property a2() As String
            Get
                Return ResourceManager.GetString("a2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11001001110.
        '''</summary>
        Friend ReadOnly Property a20() As String
            Get
                Return ResourceManager.GetString("a20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11011100100.
        '''</summary>
        Friend ReadOnly Property a21() As String
            Get
                Return ResourceManager.GetString("a21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11001110100.
        '''</summary>
        Friend ReadOnly Property a22() As String
            Get
                Return ResourceManager.GetString("a22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11101101110.
        '''</summary>
        Friend ReadOnly Property a23() As String
            Get
                Return ResourceManager.GetString("a23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11101001100.
        '''</summary>
        Friend ReadOnly Property a24() As String
            Get
                Return ResourceManager.GetString("a24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11100101100.
        '''</summary>
        Friend ReadOnly Property a25() As String
            Get
                Return ResourceManager.GetString("a25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11100100110.
        '''</summary>
        Friend ReadOnly Property a26() As String
            Get
                Return ResourceManager.GetString("a26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11101100100.
        '''</summary>
        Friend ReadOnly Property a27() As String
            Get
                Return ResourceManager.GetString("a27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11100110100.
        '''</summary>
        Friend ReadOnly Property a28() As String
            Get
                Return ResourceManager.GetString("a28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11100110010.
        '''</summary>
        Friend ReadOnly Property a29() As String
            Get
                Return ResourceManager.GetString("a29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10010011000.
        '''</summary>
        Friend ReadOnly Property a3() As String
            Get
                Return ResourceManager.GetString("a3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11011011000.
        '''</summary>
        Friend ReadOnly Property a30() As String
            Get
                Return ResourceManager.GetString("a30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11011000110.
        '''</summary>
        Friend ReadOnly Property a31() As String
            Get
                Return ResourceManager.GetString("a31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11000110110.
        '''</summary>
        Friend ReadOnly Property a32() As String
            Get
                Return ResourceManager.GetString("a32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10100011000.
        '''</summary>
        Friend ReadOnly Property a33() As String
            Get
                Return ResourceManager.GetString("a33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10001011000.
        '''</summary>
        Friend ReadOnly Property a34() As String
            Get
                Return ResourceManager.GetString("a34", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10001000110.
        '''</summary>
        Friend ReadOnly Property a35() As String
            Get
                Return ResourceManager.GetString("a35", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10110001000.
        '''</summary>
        Friend ReadOnly Property a36() As String
            Get
                Return ResourceManager.GetString("a36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10001101000.
        '''</summary>
        Friend ReadOnly Property a37() As String
            Get
                Return ResourceManager.GetString("a37", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10001100010.
        '''</summary>
        Friend ReadOnly Property a38() As String
            Get
                Return ResourceManager.GetString("a38", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11010001000.
        '''</summary>
        Friend ReadOnly Property a39() As String
            Get
                Return ResourceManager.GetString("a39", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10010001100.
        '''</summary>
        Friend ReadOnly Property a4() As String
            Get
                Return ResourceManager.GetString("a4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11000101000.
        '''</summary>
        Friend ReadOnly Property a40() As String
            Get
                Return ResourceManager.GetString("a40", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11000100010.
        '''</summary>
        Friend ReadOnly Property a41() As String
            Get
                Return ResourceManager.GetString("a41", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10110111000.
        '''</summary>
        Friend ReadOnly Property a42() As String
            Get
                Return ResourceManager.GetString("a42", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10110001110.
        '''</summary>
        Friend ReadOnly Property a43() As String
            Get
                Return ResourceManager.GetString("a43", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10001101110.
        '''</summary>
        Friend ReadOnly Property a44() As String
            Get
                Return ResourceManager.GetString("a44", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10111011000.
        '''</summary>
        Friend ReadOnly Property a45() As String
            Get
                Return ResourceManager.GetString("a45", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10111000110.
        '''</summary>
        Friend ReadOnly Property a46() As String
            Get
                Return ResourceManager.GetString("a46", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10001110110.
        '''</summary>
        Friend ReadOnly Property a47() As String
            Get
                Return ResourceManager.GetString("a47", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11101110110.
        '''</summary>
        Friend ReadOnly Property a48() As String
            Get
                Return ResourceManager.GetString("a48", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11010001110.
        '''</summary>
        Friend ReadOnly Property a49() As String
            Get
                Return ResourceManager.GetString("a49", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10001001100.
        '''</summary>
        Friend ReadOnly Property a5() As String
            Get
                Return ResourceManager.GetString("a5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11000101110.
        '''</summary>
        Friend ReadOnly Property a50() As String
            Get
                Return ResourceManager.GetString("a50", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11011101000.
        '''</summary>
        Friend ReadOnly Property a51() As String
            Get
                Return ResourceManager.GetString("a51", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11011100010.
        '''</summary>
        Friend ReadOnly Property a52() As String
            Get
                Return ResourceManager.GetString("a52", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11011101110.
        '''</summary>
        Friend ReadOnly Property a53() As String
            Get
                Return ResourceManager.GetString("a53", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11101011000.
        '''</summary>
        Friend ReadOnly Property a54() As String
            Get
                Return ResourceManager.GetString("a54", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11101000110.
        '''</summary>
        Friend ReadOnly Property a55() As String
            Get
                Return ResourceManager.GetString("a55", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11100010110.
        '''</summary>
        Friend ReadOnly Property a56() As String
            Get
                Return ResourceManager.GetString("a56", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11101101000.
        '''</summary>
        Friend ReadOnly Property a57() As String
            Get
                Return ResourceManager.GetString("a57", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11101100010.
        '''</summary>
        Friend ReadOnly Property a58() As String
            Get
                Return ResourceManager.GetString("a58", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11100011010.
        '''</summary>
        Friend ReadOnly Property a59() As String
            Get
                Return ResourceManager.GetString("a59", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10011001000.
        '''</summary>
        Friend ReadOnly Property a6() As String
            Get
                Return ResourceManager.GetString("a6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11101111010.
        '''</summary>
        Friend ReadOnly Property a60() As String
            Get
                Return ResourceManager.GetString("a60", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11001000010.
        '''</summary>
        Friend ReadOnly Property a61() As String
            Get
                Return ResourceManager.GetString("a61", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11110001010.
        '''</summary>
        Friend ReadOnly Property a62() As String
            Get
                Return ResourceManager.GetString("a62", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10100110000.
        '''</summary>
        Friend ReadOnly Property a63() As String
            Get
                Return ResourceManager.GetString("a63", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10100001100.
        '''</summary>
        Friend ReadOnly Property a64() As String
            Get
                Return ResourceManager.GetString("a64", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10010110000.
        '''</summary>
        Friend ReadOnly Property a65() As String
            Get
                Return ResourceManager.GetString("a65", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10010000110.
        '''</summary>
        Friend ReadOnly Property a66() As String
            Get
                Return ResourceManager.GetString("a66", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10000101100.
        '''</summary>
        Friend ReadOnly Property a67() As String
            Get
                Return ResourceManager.GetString("a67", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10000100110.
        '''</summary>
        Friend ReadOnly Property a68() As String
            Get
                Return ResourceManager.GetString("a68", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10110010000.
        '''</summary>
        Friend ReadOnly Property a69() As String
            Get
                Return ResourceManager.GetString("a69", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10011000100.
        '''</summary>
        Friend ReadOnly Property a7() As String
            Get
                Return ResourceManager.GetString("a7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10110000100.
        '''</summary>
        Friend ReadOnly Property a70() As String
            Get
                Return ResourceManager.GetString("a70", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10011010000.
        '''</summary>
        Friend ReadOnly Property a71() As String
            Get
                Return ResourceManager.GetString("a71", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10011000010.
        '''</summary>
        Friend ReadOnly Property a72() As String
            Get
                Return ResourceManager.GetString("a72", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10000110100.
        '''</summary>
        Friend ReadOnly Property a73() As String
            Get
                Return ResourceManager.GetString("a73", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10000110010.
        '''</summary>
        Friend ReadOnly Property a74() As String
            Get
                Return ResourceManager.GetString("a74", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11000010010.
        '''</summary>
        Friend ReadOnly Property a75() As String
            Get
                Return ResourceManager.GetString("a75", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11001010000.
        '''</summary>
        Friend ReadOnly Property a76() As String
            Get
                Return ResourceManager.GetString("a76", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11110111010.
        '''</summary>
        Friend ReadOnly Property a77() As String
            Get
                Return ResourceManager.GetString("a77", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11000010100.
        '''</summary>
        Friend ReadOnly Property a78() As String
            Get
                Return ResourceManager.GetString("a78", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10001111010.
        '''</summary>
        Friend ReadOnly Property a79() As String
            Get
                Return ResourceManager.GetString("a79", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10001100100.
        '''</summary>
        Friend ReadOnly Property a8() As String
            Get
                Return ResourceManager.GetString("a8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10100111100.
        '''</summary>
        Friend ReadOnly Property a80() As String
            Get
                Return ResourceManager.GetString("a80", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10010111100.
        '''</summary>
        Friend ReadOnly Property a81() As String
            Get
                Return ResourceManager.GetString("a81", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10010011110.
        '''</summary>
        Friend ReadOnly Property a82() As String
            Get
                Return ResourceManager.GetString("a82", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10111100100.
        '''</summary>
        Friend ReadOnly Property a83() As String
            Get
                Return ResourceManager.GetString("a83", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10011110100.
        '''</summary>
        Friend ReadOnly Property a84() As String
            Get
                Return ResourceManager.GetString("a84", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10011110010.
        '''</summary>
        Friend ReadOnly Property a85() As String
            Get
                Return ResourceManager.GetString("a85", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11110100100.
        '''</summary>
        Friend ReadOnly Property a86() As String
            Get
                Return ResourceManager.GetString("a86", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11110010100.
        '''</summary>
        Friend ReadOnly Property a87() As String
            Get
                Return ResourceManager.GetString("a87", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11110010010.
        '''</summary>
        Friend ReadOnly Property a88() As String
            Get
                Return ResourceManager.GetString("a88", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11011011110.
        '''</summary>
        Friend ReadOnly Property a89() As String
            Get
                Return ResourceManager.GetString("a89", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11001001000.
        '''</summary>
        Friend ReadOnly Property a9() As String
            Get
                Return ResourceManager.GetString("a9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11011110110.
        '''</summary>
        Friend ReadOnly Property a90() As String
            Get
                Return ResourceManager.GetString("a90", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11110110110.
        '''</summary>
        Friend ReadOnly Property a91() As String
            Get
                Return ResourceManager.GetString("a91", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10101111000.
        '''</summary>
        Friend ReadOnly Property a92() As String
            Get
                Return ResourceManager.GetString("a92", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10100011110.
        '''</summary>
        Friend ReadOnly Property a93() As String
            Get
                Return ResourceManager.GetString("a93", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10001011110.
        '''</summary>
        Friend ReadOnly Property a94() As String
            Get
                Return ResourceManager.GetString("a94", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10111101000.
        '''</summary>
        Friend ReadOnly Property a95() As String
            Get
                Return ResourceManager.GetString("a95", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10111100010.
        '''</summary>
        Friend ReadOnly Property a96() As String
            Get
                Return ResourceManager.GetString("a96", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11110101000.
        '''</summary>
        Friend ReadOnly Property a97() As String
            Get
                Return ResourceManager.GetString("a97", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11110100010.
        '''</summary>
        Friend ReadOnly Property a98() As String
            Get
                Return ResourceManager.GetString("a98", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10111011110.
        '''</summary>
        Friend ReadOnly Property a99() As String
            Get
                Return ResourceManager.GetString("a99", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
